# Generated by Django 5.2.10 on 2026-01-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('manually_stopped', models.BooleanField(default=False)),
                ('restart_count', models.IntegerField(default=0)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dashboard.command')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
