# Generated by Django 5.2.10 on 2026-01-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_commandrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandrun',
            name='killed',
            field=models.BooleanField(default=False),
        ),
    ]
